Домашнее задание по теме: "Основы JS. Примитивные типы данных" // 02-javascript-data-types
js-tasks-ru/js-20221121_alexulanad pull request #2
Opened 2022-11-26 12:09 UTC by alexulanad

1. Реализована функция: 1-sort-strings, сортирующая массив строк, по убыванию или возрастанию, с учетом диакритических знаков и приоритетности символов прописных букв.

2. Реализована функция: pick, фильтруюшая объект, по критерию совпадения с значениями, заданных полей.

3. Реализована функция: omit, фильтрующая объект, по критерию исключения совпадений с значениями, заданных полей.

2022-11-26 12:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-26 19:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-27 09:37 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const arrCopy = [...arr];
good 👍

2022-11-27 09:38 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return arrCopy.sort( (a, b) => new Intl.Collator(["ru", "en-GB", "en-US"], {caseFirst: "upper"}).compare(a, b)).reverse();
в решении явно присутствуют дубликаты кода, от них следует избавится

2022-11-27 09:38 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return arrCopy.sort( (a, b) => new Intl.Collator(["ru", "en-GB", "en-US"], {caseFirst: "upper"}).compare(a, b)).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-11-27 09:38 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(Object.entries(obj).filter((item) => { return fields.includes(item[0]); }));
good 👍

2022-11-27 09:39 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(Object.entries(obj).filter((item) => { return !fields.includes(item[0]); }));
good 👍
но было бы неплохо не делать решение в одну строку, а разбить на несколько отдельных операций

2022-11-27 09:39 UTC, dosandk requested changes
решение sortStrings следует поправить

2022-11-28 14:22 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-28 14:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-28 15:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-28 15:51 UTC, closed without merging